### ISSUE TITLE
Always display the Online option when Present

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_frontend#218]
### Current display
Right now in the catalog when we have two or more print holdings and and an online portfolio or 856 link we do not display the online link, we do display in the all search catalog tray. Example record https://allsearch.princeton.edu/?q=science and https://catalog.princeton.edu/catalog/998574693506421.

### Desired display
Always display the online option when it's present. 

### Acceptance criteria

- [ ] Whenever a record has online holdings (portfolios or 856 links) the Online availability badge should be displayed, independent of any print holdings. 
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
  - axe dev tools
  - Lighthouse
  - Wave
- [ ] ...

**Comment by maxkadel** [comment]
Are we sure this is what we want to do? It seems like many (most?) users would be most interested in online availability, especially from the all search page? 

Maybe a good compromise would be to show one physical and one online holding, and then some version of "see more holdings on the record page"?

**Comment by christinach** [comment]
Or keep both print holdings and display message: 'See record for online holdings.'

**Comment by kelea99** [comment]
Examples from Peer Institutions for All Search Results "Science", and online holdings mentions:
## Harvard (Note "More Print and Online Options" at top of one result)
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUZuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--707c7b255f535da693183c7b36b70ad79557c747/Screenshot%202024-02-16%20at%2011.35.52%E2%80%AFAM%20%282%29.png" alt="Screenshot 2024-02-16 at 11.35.52 AM (2).png" />

## Stanford (links direct on search, noting pdf or otherwise)
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--290c27e2147931863f7dfebd46bb1105a1e0850f/Screenshot%202024-02-16%20at%2011.38.58%E2%80%AFAM%20%282%29.png" alt="Screenshot 2024-02-16 at 11.38.58 AM (2).png" />

## Columbia (note icons for online / print in results)
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVpuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84ebe1fab0b6a4b8bcbe5559ccb723a93c0e32b4/Screenshot%202024-02-16%20at%2011.36.37%E2%80%AFAM%20%282%29.png" alt="Screenshot 2024-02-16 at 11.36.37 AM (2).png" />

## Penn (nothing at all)
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d05da69d70cd90ab0412ad595ddb8945c2bdb771/Screenshot%202024-02-16%20at%2011.40.19%E2%80%AFAM%20%282%29.png" alt="Screenshot 2024-02-16 at 11.40.19 AM (2).png" />

**Comment by maxkadel** [comment]
It looks like Penn has link text that says, for example, "8 print options" or "15 online options"

**Comment by kevinreiss** [comment]
Based on our discussions with @Ka-YT it seems like we should Always note the availability of online options in any discovery interface.

**Comment by rladdusaw** [comment]
The metadata [component](https://github.com/pulibrary/allsearch_frontend/blob/main/src/components/metadata/CatalogMetadata.vue#L5-L7) for the catalog will always display the online content if there is a url. Closing this issue as resolved.
